"""
Information — local buffer for multimodal inputs.

Nothing is written to ApertureDB until Memory.commit() is called.
Validation happens eagerly at log() time to surface errors as close
to the problem as possible — before any DB or model interaction.

Example:
    info = Information(context_id=ctx.id)
    info.log(text="Customer says order #4821 never arrived")
    info.log(image="screenshot.png")
    info.log(video="recording.mp4")
    info.log(blob="contract.pdf", document_type="pdf")
    memory.commit(ctx, info)
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import numpy as np
from PIL import Image as PILImage

from aperture_nexus.exceptions import NexusValidationError

logger = logging.getLogger(__name__)

# Accepted numpy dtypes for image arrays
_IMAGE_DTYPES = {np.dtype("uint8"), np.dtype("float32")}

# Accepted number of channels for image arrays
_IMAGE_CHANNELS = {1, 3, 4}

# Property keys managed by aperture-nexus — callers may not override these
_RESERVED_METADATA_KEYS = frozenset({
    "context_id", "session_id", "user_id", "created_at",
    "document_type", "text_preview", "text",
    "embedding_model", "modality", "start_frame", "stop_frame",
})

# ApertureDB accepts only these scalar types as entity/object properties
_METADATA_VALUE_TYPES = (str, int, float, bool)


@dataclass
class InformationEntry:
    """One entry added via ``Information.log()``.

    Returned by ``log()`` so the caller can hold a reference and pass
    it to ``remove()`` later. Treat this as an opaque handle — do not
    construct instances directly or mutate fields.
    """

    text: Optional[str] = None
    image: Optional[Any] = None   # PIL.Image, np.ndarray, bytes, or str
    video: Optional[Any] = None   # str (path/url) or bytes
    blob: Optional[Any] = None    # str (path/url) or bytes
    document_type: Optional[str] = None
    embedding: Optional[np.ndarray] = None
    embedding_model: Optional[str] = None
    # Per-clip embeddings generated by embed_video() — one per segment.
    # Each item: (embedding_vector, {"start_frame": int, "stop_frame": int}).
    # Set by Memory._generate_missing_embeddings(); None for pre-computed
    # single embeddings supplied by the caller via info.log(embedding=...).
    video_clip_embeddings: Optional[list] = None
    metadata: Optional[dict] = None
    tag: Optional[str] = None
    logged_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


@dataclass
class _PendingConnection:
    """Internal: one connect() call buffered before commit."""
    target_id: str
    relationship: str
    properties: dict


class Information:
    """Local buffer for multimodal inputs.

    Nothing is written to ApertureDB until Memory.commit() is called.
    Validation happens eagerly at log() time — bad inputs raise
    NexusValidationError immediately, before any DB or model call.

    Args:
        context_id: ID of the Context this information belongs to.
            Use ``ctx.id``.

    Example:
        info = Information(context_id=ctx.id)

        # Text
        info.log(text="Customer says order #4821 never arrived")

        # Image — any form
        info.log(image="screenshot.png")
        info.log(image="https://example.com/photo.jpg")
        info.log(image=pil_image)
        info.log(image=numpy_array)

        # Video
        info.log(video="recording.mp4")

        # Blob — document_type required
        info.log(blob=pdf_bytes, document_type="pdf")

        # Metadata — arbitrary key-value properties stored alongside the entry
        info.log(text="Order #4821 missing", metadata={"ticket_id": "T-99", "priority": 1})
        info.log(image="photo.jpg", metadata={"source": "webcam", "location": "lobby"})

        # Combined — one log entry, multiple modalities
        info.log(text="See attached", blob=pdf_bytes, document_type="pdf")

        # Pre-computed embedding — skips model call at commit time
        info.log(
            image=img,
            embedding=my_vector,
            embedding_model="clip-vit-base-patch32",
        )
    """

    def __init__(self, context_id: str) -> None:
        if not isinstance(context_id, str) or not context_id.strip():
            raise NexusValidationError(
                "context_id must be a non-empty string. "
                "Use ctx.id from a Context instance."
            )
        self.context_id = context_id
        self._entries: list[InformationEntry] = []
        self._pending_connections: list[_PendingConnection] = []
        logger.debug(
            "Information buffer created: context_id=%r", context_id
        )

    def log(
        self,
        text: Optional[str] = None,
        image: Optional[Any] = None,
        video: Optional[Any] = None,
        blob: Optional[Any] = None,
        document_type: Optional[str] = None,
        embedding: Optional[np.ndarray] = None,
        embedding_model: Optional[str] = None,
        metadata: Optional[dict] = None,
        tag: Optional[str] = None,
    ) -> "InformationEntry":
        """Add one entry to the buffer and return it.

        Multiple modalities can be combined in a single call (e.g.
        text + blob for "see attached PDF"). Validation happens
        immediately — bad inputs raise NexusValidationError before
        anything is stored.

        The returned ``InformationEntry`` can be passed to
        ``remove()`` to discard the entry before it is committed.

        Args:
            text: Plain text. Long text is chunked automatically at
                commit time.
            image: Image in any common form: file path, URL, bytes,
                PIL Image, or numpy array (HW or HWC uint8/float32).
                File existence and read permission are checked
                immediately; content validity is checked at commit time.
            video: Video file path, URL, or raw bytes.
                File existence and read permission are checked
                immediately; content validity is checked at commit time.
            blob: File path, URL, or raw bytes for any binary format.
                Requires ``document_type``. File existence and read
                permission are checked immediately.
            document_type: File extension for blobs: ``"pdf"``,
                ``"mp3"``, ``"docx"``, ``"csv"``, etc.
            embedding: Pre-computed embedding vector (1D float array).
                Skips model call at commit time. Requires
                ``embedding_model``.
            embedding_model: Name of the model that produced the
                embedding. Required when ``embedding`` is provided.
            metadata: Arbitrary key-value properties stored alongside
                the entry in ApertureDB. Keys must be strings; values
                must be ``str``, ``int``, ``float``, or ``bool``.
                Reserved keys (``context_id``, ``session_id``, etc.)
                are rejected — use the Context fields for those.
            tag: Optional label for this entry. Use the same tag on a
                group of related entries and call ``remove_tagged()``
                to discard them all at once.

        Returns:
            The ``InformationEntry`` that was added. Hold a reference
            and pass it to ``remove()`` to discard it later.

        Raises:
            NexusValidationError: If input is invalid (missing file,
                permission denied, wrong numpy shape, missing
                document_type for blob, embedding provided without
                embedding_model, invalid metadata key/value types,
                reserved key used, etc.)

        Example:
            entry = info.log(text="preliminary note")
            if changed_my_mind:
                info.remove(entry)

            # Tag a group for atomic discard:
            info.log(text="Order #4412 placed", tag="order-4412")
            info.log(blob=receipt, document_type="pdf", tag="order-4412")
            if order_cancelled:
                info.remove_tagged("order-4412")
        """
        if all(v is None for v in [text, image, video, blob]):
            raise NexusValidationError(
                "At least one of text, image, video, or blob "
                "must be provided."
            )

        validated_text = _validate_text(text)
        validated_image = _validate_image(image)
        validated_video = _validate_video(video)
        validated_blob, validated_doc_type = _validate_blob(
            blob, document_type
        )
        validated_emb, validated_emb_model = _validate_embedding(
            embedding, embedding_model
        )
        validated_metadata = _validate_metadata(metadata)
        validated_tag = _validate_tag(tag)

        entry = InformationEntry(
            text=validated_text,
            image=validated_image,
            video=validated_video,
            blob=validated_blob,
            document_type=validated_doc_type,
            embedding=validated_emb,
            embedding_model=validated_emb_model,
            metadata=validated_metadata,
            tag=validated_tag,
        )
        self._entries.append(entry)
        logger.debug(
            "Logged entry %d for context_id=%r tag=%r",
            len(self._entries),
            self.context_id,
            validated_tag,
        )
        return entry

    def connect(
        self,
        target: str,
        relationship: str,
        properties: Optional[dict] = None,
    ) -> None:
        """Buffer a connection to write when Memory.commit() is called.

        Creates a ``nexus_link`` connection from this context to the target
        context when committed. Use this to express relationships that should
        be written atomically with the content being logged.

        Args:
            target: ``context_id`` of the target ``Context``.
            relationship: Relationship type, e.g. ``"follows"``,
                ``"caused_by"``, ``"references"``.
            properties: Optional extra properties on the connection.

        Raises:
            NexusValidationError: If ``target`` is empty or
                ``relationship`` is empty.

        Example:
            info.log(text="Follow-up to previous analysis")
            info.connect(target=prev_ctx.id, relationship="follows")
            memory.commit(ctx, info)  # writes both the text and the link
        """
        if not isinstance(target, str) or not target.strip():
            raise NexusValidationError(
                "target must be a non-empty context_id string. "
                "Pass ctx.id of the target Context."
            )
        if not isinstance(relationship, str) or not relationship.strip():
            raise NexusValidationError(
                "relationship must be a non-empty string. "
                "Examples: 'follows', 'caused_by', 'references'."
            )
        self._pending_connections.append(_PendingConnection(
            target_id=target.strip(),
            relationship=relationship.strip(),
            properties=dict(properties) if properties else {},
        ))
        logger.debug(
            "Buffered connection -[%s]-> %r for context_id=%r",
            relationship, target, self.context_id,
        )

    def remove_all(self) -> None:
        """Remove all pending entries and connections from the buffer.

        Entries are discarded without being committed to ApertureDB.
        Use this to abandon a work-in-progress log before starting
        over — for example after an upstream error invalidated the
        current batch.

        Does not affect entries already committed via
        ``Memory.commit()``.

        Example:
            info.log(text="preliminary note")
            info.log(image="draft.png")
            info.remove_all()    # start over — nothing committed yet
            info.log(text="final note")
            memory.commit(ctx, info)
        """
        count = len(self._entries)
        self._entries.clear()
        self._pending_connections.clear()
        logger.debug(
            "Information buffer cleared (remove_all): %d entries discarded,"
            " context_id=%r",
            count,
            self.context_id,
        )

    def remove(self, entry: "InformationEntry") -> bool:
        """Remove a specific pending entry from the buffer.

        Uses identity comparison (``is``), not equality. Pass back the
        object returned by ``log()`` — do not construct a new instance.

        Args:
            entry: The ``InformationEntry`` returned by ``log()``.

        Returns:
            ``True`` if the entry was found and removed; ``False`` if
            it was not in the buffer (already committed or already
            removed).

        Raises:
            NexusValidationError: If ``entry`` is not an
                ``InformationEntry`` instance.

        Example:
            entry = info.log(text="preliminary note")
            # … decide the note was wrong …
            info.remove(entry)   # removed — will not be committed
        """
        if not isinstance(entry, InformationEntry):
            raise NexusValidationError(
                "entry must be an InformationEntry returned by log(). "
                f"Got {type(entry).__name__!r}."
            )
        for i, e in enumerate(self._entries):
            if e is entry:
                self._entries.pop(i)
                logger.debug(
                    "Removed entry (tag=%r) for context_id=%r",
                    entry.tag, self.context_id,
                )
                return True
        return False

    def remove_tagged(self, tag: str) -> int:
        """Remove all pending entries with the given tag.

        Entries added via ``log(tag=...)`` that share the same tag
        are discarded atomically. Useful for cancelling a logical
        group of entries before commit.

        Args:
            tag: The tag value to match. Must be non-empty.

        Returns:
            Number of entries removed (0 if none matched).

        Raises:
            NexusValidationError: If ``tag`` is not a non-empty string.

        Example:
            info.log(text="Order #4412 placed", tag="order-4412")
            info.log(blob=receipt, document_type="pdf", tag="order-4412")
            if order_cancelled:
                removed = info.remove_tagged("order-4412")  # removes 2
        """
        if not isinstance(tag, str) or not tag.strip():
            raise NexusValidationError(
                "tag must be a non-empty string. "
                "Use the same tag you passed to log(tag=...) when logging the entries."
            )
        before = len(self._entries)
        self._entries = [e for e in self._entries if e.tag != tag]
        removed = before - len(self._entries)
        logger.debug(
            "remove_tagged(%r): removed %d entries for context_id=%r",
            tag, removed, self.context_id,
        )
        return removed

    def remove_before(self, timestamp: datetime) -> int:
        """Remove all pending entries logged before a timestamp.

        Discards older staged entries while keeping more recent ones.
        Useful for trimming a buffer that has accumulated stale context
        from earlier in a session.

        For the inverse (rollback: discard everything logged *since* a
        checkpoint, keep what came before), use ``remove_since()``.

        Args:
            timestamp: UTC-aware ``datetime``. Entries whose
                ``logged_at`` is strictly earlier than this value are
                removed. Must be timezone-aware (use
                ``datetime.now(timezone.utc)`` or equivalent).

        Returns:
            Number of entries removed (0 if none matched).

        Raises:
            NexusValidationError: If ``timestamp`` is not a
                timezone-aware ``datetime``.

        Example:
            from datetime import datetime, timezone

            # Discard anything logged before the last hour:
            cutoff = datetime.now(timezone.utc) - timedelta(hours=1)
            info.remove_before(cutoff)  # stale entries gone, recent kept
        """
        if not isinstance(timestamp, datetime):
            raise NexusValidationError(
                "timestamp must be a datetime instance. "
                f"Got {type(timestamp).__name__!r}."
            )
        if timestamp.tzinfo is None:
            raise NexusValidationError(
                "timestamp must be timezone-aware. "
                "Use datetime.now(timezone.utc) or attach tzinfo explicitly."
            )
        before = len(self._entries)
        self._entries = [
            e for e in self._entries if e.logged_at >= timestamp
        ]
        removed = before - len(self._entries)
        logger.debug(
            "remove_before(%s): removed %d entries for context_id=%r",
            timestamp.isoformat(), removed, self.context_id,
        )
        return removed

    def remove_since(self, checkpoint: datetime) -> int:
        """Remove all pending entries logged at or after a checkpoint.

        Use this for rollback: capture a checkpoint before a block of
        ``log()`` calls, then call ``remove_since(checkpoint)`` to
        undo all logging since that point.

        Args:
            checkpoint: UTC-aware ``datetime``. Entries whose
                ``logged_at`` is greater than or equal to this value
                are removed. Must be timezone-aware (use
                ``datetime.now(timezone.utc)`` or equivalent).

        Returns:
            Number of entries removed (0 if none matched).

        Raises:
            NexusValidationError: If ``checkpoint`` is not a
                timezone-aware ``datetime``.

        Example:
            from datetime import datetime, timezone

            checkpoint = datetime.now(timezone.utc)
            info.log(text="attempt A")
            info.log(image="draft.png")
            # … something went wrong, undo the whole attempt …
            info.remove_since(checkpoint)  # back to state at checkpoint
        """
        if not isinstance(checkpoint, datetime):
            raise NexusValidationError(
                "checkpoint must be a datetime instance. "
                f"Got {type(checkpoint).__name__!r}."
            )
        if checkpoint.tzinfo is None:
            raise NexusValidationError(
                "checkpoint must be timezone-aware. "
                "Use datetime.now(timezone.utc) or attach tzinfo explicitly."
            )
        before = len(self._entries)
        self._entries = [
            e for e in self._entries if e.logged_at < checkpoint
        ]
        removed = before - len(self._entries)
        logger.debug(
            "remove_since(%s): removed %d entries for context_id=%r",
            checkpoint.isoformat(), removed, self.context_id,
        )
        return removed

    def _drain(self) -> list["InformationEntry"]:
        """Return all buffered entries and reset the buffer.

        Called by Memory after a successful commit. Matches the
        standard checkpoint pattern: the buffer is reused across
        commits rather than discarded.
        """
        entries, self._entries = self._entries, []
        self._pending_connections = []
        return entries

    def __len__(self) -> int:
        """Return the number of pending (uncommitted) entries."""
        return len(self._entries)

    def __repr__(self) -> str:
        return (
            f"Information(context_id={self.context_id!r},"
            f" entries={len(self._entries)})"
        )


# ---------------------------------------------------------------------------
# Validation helpers — module-private
# ---------------------------------------------------------------------------


def _validate_tag(tag: Optional[str]) -> Optional[str]:
    if tag is None:
        return None
    if not isinstance(tag, str):
        raise NexusValidationError(
            f"tag must be a string. Got {type(tag).__name__!r}."
        )
    if not tag.strip():
        raise NexusValidationError("tag must not be empty.")
    return tag


def _validate_text(text: Optional[str]) -> Optional[str]:
    if text is None:
        return None
    if not isinstance(text, str):
        raise NexusValidationError(
            f"text must be a string. Got {type(text).__name__!r}."
        )
    if not text.strip():
        raise NexusValidationError(
            "text must not be empty. "
            "Provide a non-empty string or omit text= entirely."
        )
    return text


def _validate_image(image: Optional[Any]) -> Optional[Any]:
    if image is None:
        return None

    if isinstance(image, str):
        if image.startswith(("http://", "https://")):
            return image  # URL — reachability checked at commit time
        path = Path(image)
        if not path.is_file():
            raise NexusValidationError(
                f"Image file not found: {image}. "
                "Provide a valid file path, URL, PIL Image, "
                "numpy array, or raw bytes."
            )
        try:
            path.open("rb").close()
        except PermissionError:
            raise NexusValidationError(
                f"Image file is not readable (permission denied): {image}. "
                "Check file permissions (e.g. chmod 644) or copy the file "
                "to a readable location."
            )
        return image

    if isinstance(image, bytes):
        return image

    if isinstance(image, PILImage.Image):
        return image

    if isinstance(image, np.ndarray):
        _validate_image_ndarray(image)
        return image

    raise NexusValidationError(
        f"Unsupported image type: {type(image).__name__!r}. "
        "Provide a file path, URL, bytes, PIL Image, or numpy array."
    )


def _validate_image_ndarray(arr: np.ndarray) -> None:
    if arr.ndim not in {2, 3}:
        raise NexusValidationError(
            "Image numpy array must be 2D (H, W) or 3D (H, W, C). "
            f"Got shape {arr.shape}."
        )
    if arr.ndim == 3 and arr.shape[2] not in _IMAGE_CHANNELS:
        raise NexusValidationError(
            "Image array channel count must be 1, 3, or 4. "
            f"Got shape {arr.shape}."
        )
    if arr.dtype not in _IMAGE_DTYPES:
        raise NexusValidationError(
            f"Image array dtype must be uint8 or float32. "
            f"Got {arr.dtype}."
        )


def _validate_video(video: Optional[Any]) -> Optional[Any]:
    if video is None:
        return None

    if isinstance(video, str):
        if video.startswith(("http://", "https://")):
            return video  # URL — reachability checked at commit time
        path = Path(video)
        if not path.is_file():
            raise NexusValidationError(
                f"Video file not found: {video}. "
                "Provide a valid file path, URL, or raw bytes."
            )
        try:
            path.open("rb").close()
        except PermissionError:
            raise NexusValidationError(
                f"Video file is not readable (permission denied): {video}. "
                "Check file permissions (e.g. chmod 644) or copy the file "
                "to a readable location."
            )
        return video

    if isinstance(video, bytes):
        return video

    raise NexusValidationError(
        f"Unsupported video type: {type(video).__name__!r}. "
        "Provide a file path, URL, or bytes."
    )


def _validate_blob(
    blob: Optional[Any],
    document_type: Optional[str],
) -> tuple[Optional[Any], Optional[str]]:
    if blob is None:
        if document_type is not None:
            raise NexusValidationError(
                "document_type provided but blob is None. "
                "Provide blob=<path>, blob=<url>, or blob=<bytes> "
                "alongside document_type."
            )
        return None, None

    if isinstance(blob, str):
        if blob.startswith(("http://", "https://")):
            pass  # URL — reachability checked at commit time
        else:
            path = Path(blob)
            if not path.is_file():
                raise NexusValidationError(
                    f"Blob file not found: {blob}. "
                    "Provide a valid file path, URL, or raw bytes."
                )
            try:
                path.open("rb").close()
            except PermissionError:
                raise NexusValidationError(
                    f"Blob file is not readable (permission denied): {blob}. "
                    "Check file permissions (e.g. chmod 644) or copy the file "
                    "to a readable location."
                )
    elif not isinstance(blob, bytes):
        raise NexusValidationError(
            f"blob must be a file path, URL, or bytes. "
            f"Got {type(blob).__name__!r}."
        )

    if not document_type:
        raise NexusValidationError(
            "document_type is required when blob is provided. "
            'Examples: "pdf", "mp3", "docx", "csv".'
        )

    if not isinstance(document_type, str) or not document_type.strip():
        raise NexusValidationError(
            "document_type must be a non-empty string. "
            'Examples: "pdf", "mp3", "docx".'
        )

    return blob, document_type.strip().lower()


def _validate_metadata(
    metadata: Optional[dict],
) -> Optional[dict]:
    if metadata is None:
        return None
    if not isinstance(metadata, dict):
        raise NexusValidationError(
            f"metadata must be a dict. Got {type(metadata).__name__!r}."
        )
    for key, value in metadata.items():
        if not isinstance(key, str):
            raise NexusValidationError(
                f"metadata keys must be strings. Got {type(key).__name__!r}."
            )
        if key in _RESERVED_METADATA_KEYS:
            raise NexusValidationError(
                f"metadata key {key!r} is reserved by aperture-nexus. "
                f"Use the Context fields for session/user identity."
            )
        if not isinstance(value, _METADATA_VALUE_TYPES):
            raise NexusValidationError(
                f"metadata[{key!r}] has unsupported type "
                f"{type(value).__name__!r}. "
                f"Use str, int, float, or bool."
            )
    return dict(metadata)


def _validate_embedding(
    embedding: Optional[np.ndarray],
    embedding_model: Optional[str],
) -> tuple[Optional[np.ndarray], Optional[str]]:
    if embedding is None:
        return None, None

    if not isinstance(embedding, np.ndarray):
        raise NexusValidationError(
            "embedding must be a numpy array. "
            f"Got {type(embedding).__name__!r}."
        )

    if embedding.ndim != 1:
        raise NexusValidationError(
            "embedding must be a 1D array. "
            f"Got shape {embedding.shape}."
        )

    if not np.issubdtype(embedding.dtype, np.floating):
        raise NexusValidationError(
            "embedding dtype must be a float type. "
            f"Got {embedding.dtype}. "
            "Cast before passing: embedding.astype(np.float32)."
        )

    if not embedding_model:
        raise NexusValidationError(
            "embedding_model is required when embedding is provided. "
            "Provide the name of the model that produced the embedding "
            "(e.g. 'ViT-B/16', 'text-embedding-3-small')."
        )

    if not isinstance(embedding_model, str) or not embedding_model.strip():
        raise NexusValidationError(
            "embedding_model must be a non-empty string."
        )

    if any(c in embedding_model for c in ('"', "\\")):
        raise NexusValidationError(
            f"embedding_model {embedding_model!r} contains a character that is "
            "not valid in an ApertureDB DescriptorSet name. "
            'Remove double-quotes and backslashes (e.g. use "ViT-B/16" not "ViT-B\\"16").'
        )

    if any(ord(c) < 32 for c in embedding_model):
        raise NexusValidationError(
            f"embedding_model {embedding_model!r} contains a control character. "
            "Use a plain printable string (e.g. 'ViT-B/16')."
        )

    return embedding, embedding_model.strip()
