"""
Information — local buffer for multimodal inputs.

Nothing is written to ApertureDB until Memory.commit() is called.
Validation happens eagerly at log() time to surface errors as close
to the problem as possible — before any DB or model interaction.

Example:
    info = Information(context_id=ctx.id)
    info.log(text="Customer says order #4821 never arrived")
    info.log(image="screenshot.png")
    info.log(video="recording.mp4")
    info.log(blob="contract.pdf", document_type="pdf")
    memory.commit(ctx, info)
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import numpy as np
from PIL import Image as PILImage

from aperture_nexus.exceptions import NexusValidationError

logger = logging.getLogger(__name__)

# Accepted numpy dtypes for image arrays
_IMAGE_DTYPES = {np.dtype("uint8"), np.dtype("float32")}

# Accepted number of channels for image arrays
_IMAGE_CHANNELS = {1, 3, 4}

# Property keys managed by aperture-nexus — callers may not override these
_RESERVED_METADATA_KEYS = frozenset({
    "context_id", "session_id", "user_id", "created_at",
    "document_type", "text_preview", "text",
    "embedding_model", "modality", "start_frame", "stop_frame",
})

# ApertureDB accepts only these scalar types as entity/object properties
_METADATA_VALUE_TYPES = (str, int, float, bool)


@dataclass
class _LogEntry:
    """Internal: one item added via Information.log()."""

    text: Optional[str] = None
    image: Optional[Any] = None   # PIL.Image, np.ndarray, bytes, or str
    video: Optional[Any] = None   # str (path/url) or bytes
    blob: Optional[Any] = None    # str (path/url) or bytes
    document_type: Optional[str] = None
    embedding: Optional[np.ndarray] = None
    embedding_model: Optional[str] = None
    # Per-clip embeddings generated by embed_video() — one per segment.
    # Each item: (embedding_vector, {"start_frame": int, "stop_frame": int}).
    # Set by Memory._generate_missing_embeddings(); None for pre-computed
    # single embeddings supplied by the caller via info.log(embedding=...).
    video_clip_embeddings: Optional[list] = None
    metadata: Optional[dict] = None


@dataclass
class _PendingConnection:
    """Internal: one connect() call buffered before commit."""
    target_id: str
    relationship: str
    properties: dict


class Information:
    """Local buffer for multimodal inputs.

    Nothing is written to ApertureDB until Memory.commit() is called.
    Validation happens eagerly at log() time — bad inputs raise
    NexusValidationError immediately, before any DB or model call.

    Args:
        context_id: ID of the Context this information belongs to.
            Use ``ctx.id``.

    Example:
        info = Information(context_id=ctx.id)

        # Text
        info.log(text="Customer says order #4821 never arrived")

        # Image — any form
        info.log(image="screenshot.png")
        info.log(image="https://example.com/photo.jpg")
        info.log(image=pil_image)
        info.log(image=numpy_array)

        # Video
        info.log(video="recording.mp4")

        # Blob — document_type required
        info.log(blob=pdf_bytes, document_type="pdf")

        # Metadata — arbitrary key-value properties stored alongside the entry
        info.log(text="Order #4821 missing", metadata={"ticket_id": "T-99", "priority": 1})
        info.log(image="photo.jpg", metadata={"source": "webcam", "location": "lobby"})

        # Combined — one log entry, multiple modalities
        info.log(text="See attached", blob=pdf_bytes, document_type="pdf")

        # Pre-computed embedding — skips model call at commit time
        info.log(
            image=img,
            embedding=my_vector,
            embedding_model="clip-vit-base-patch32",
        )
    """

    def __init__(self, context_id: str) -> None:
        if not isinstance(context_id, str) or not context_id.strip():
            raise NexusValidationError(
                "context_id must be a non-empty string. "
                "Use ctx.id from a Context instance."
            )
        self.context_id = context_id
        self._entries: list[_LogEntry] = []
        self._pending_connections: list[_PendingConnection] = []
        logger.debug(
            "Information buffer created: context_id=%r", context_id
        )

    def log(
        self,
        text: Optional[str] = None,
        image: Optional[Any] = None,
        video: Optional[Any] = None,
        blob: Optional[Any] = None,
        document_type: Optional[str] = None,
        embedding: Optional[np.ndarray] = None,
        embedding_model: Optional[str] = None,
        metadata: Optional[dict] = None,
    ) -> None:
        """Add one entry to the buffer.

        Multiple modalities can be combined in a single call (e.g.
        text + blob for "see attached PDF"). Validation happens
        immediately — bad inputs raise NexusValidationError before
        anything is stored.

        Args:
            text: Plain text. Long text is chunked automatically at
                commit time.
            image: Image in any common form: file path, URL, bytes,
                PIL Image, or numpy array (HW or HWC uint8/float32).
            video: Video file path, URL, or raw bytes.
            blob: File path, URL, or raw bytes for any binary format.
                Requires ``document_type``. Paths and URLs are
                resolved at commit time.
            document_type: File extension for blobs: ``"pdf"``,
                ``"mp3"``, ``"docx"``, ``"csv"``, etc.
            embedding: Pre-computed embedding vector (1D float array).
                Skips model call at commit time. Requires
                ``embedding_model``.
            embedding_model: Name of the model that produced the
                embedding. Required when ``embedding`` is provided.
            metadata: Arbitrary key-value properties stored alongside
                the entry in ApertureDB. Keys must be strings; values
                must be ``str``, ``int``, ``float``, or ``bool``.
                Reserved keys (``context_id``, ``session_id``, etc.)
                are rejected — use the Context fields for those.

        Raises:
            NexusValidationError: If input is invalid (missing file,
                wrong numpy shape, missing document_type for blob,
                embedding provided without embedding_model,
                invalid metadata key/value types, reserved key used,
                etc.)
        """
        if all(v is None for v in [text, image, video, blob]):
            raise NexusValidationError(
                "At least one of text, image, video, or blob "
                "must be provided."
            )

        validated_text = _validate_text(text)
        validated_image = _validate_image(image)
        validated_video = _validate_video(video)
        validated_blob, validated_doc_type = _validate_blob(
            blob, document_type
        )
        validated_emb, validated_emb_model = _validate_embedding(
            embedding, embedding_model
        )
        validated_metadata = _validate_metadata(metadata)

        entry = _LogEntry(
            text=validated_text,
            image=validated_image,
            video=validated_video,
            blob=validated_blob,
            document_type=validated_doc_type,
            embedding=validated_emb,
            embedding_model=validated_emb_model,
            metadata=validated_metadata,
        )
        self._entries.append(entry)
        logger.debug(
            "Logged entry %d for context_id=%r",
            len(self._entries),
            self.context_id,
        )

    def connect(
        self,
        target: str,
        relationship: str,
        properties: Optional[dict] = None,
    ) -> None:
        """Buffer a connection to write when Memory.commit() is called.

        Creates a ``nexus_link`` connection from this context to the target
        context when committed. Use this to express relationships that should
        be written atomically with the content being logged.

        Args:
            target: ``context_id`` of the target ``Context``.
            relationship: Relationship type, e.g. ``"follows"``,
                ``"caused_by"``, ``"references"``.
            properties: Optional extra properties on the connection.

        Raises:
            NexusValidationError: If ``target`` is empty or
                ``relationship`` is empty.

        Example:
            info.log(text="Follow-up to previous analysis")
            info.connect(target=prev_ctx.id, relationship="follows")
            memory.commit(ctx, info)  # writes both the text and the link
        """
        if not isinstance(target, str) or not target.strip():
            raise NexusValidationError(
                "target must be a non-empty context_id string."
            )
        if not isinstance(relationship, str) or not relationship.strip():
            raise NexusValidationError(
                "relationship must be a non-empty string."
            )
        self._pending_connections.append(_PendingConnection(
            target_id=target.strip(),
            relationship=relationship.strip(),
            properties=dict(properties) if properties else {},
        ))
        logger.debug(
            "Buffered connection -[%s]-> %r for context_id=%r",
            relationship, target, self.context_id,
        )

    def remove_all(self) -> None:
        """Remove all pending entries and connections from the buffer.

        Entries are discarded without being committed to ApertureDB.
        Use this to abandon a work-in-progress log before starting
        over — for example after an upstream error invalidated the
        current batch.

        Does not affect entries already committed via
        ``Memory.commit()``.

        Example:
            info.log(text="preliminary note")
            info.log(image="draft.png")
            info.remove_all()    # start over — nothing committed yet
            info.log(text="final note")
            memory.commit(ctx, info)
        """
        count = len(self._entries)
        self._entries.clear()
        self._pending_connections.clear()
        logger.debug(
            "Information buffer cleared (remove_all): %d entries discarded,"
            " context_id=%r",
            count,
            self.context_id,
        )

    def remove(self, index: int) -> None:
        """Remove a single pending entry from the buffer by position.

        Use ``len(info)`` to get the current count. The index is
        0-based and follows the order entries were added via
        ``log()``. Consistent with ``memory.remove()`` which removes
        a committed memory by ID.

        Args:
            index: 0-based position of the entry to remove.

        Raises:
            IndexError: If ``index`` is out of range.
            NexusValidationError: If ``index`` is not an integer.

        Example:
            info.log(text="stale note — remove this")
            info.log(image="screenshot.png")
            info.remove(0)   # discard the first entry
            # only screenshot.png entry will be committed
        """
        if not isinstance(index, int):
            raise NexusValidationError(
                f"index must be an integer. "
                f"Got {type(index).__name__!r}."
            )
        n = len(self._entries)
        if n == 0:
            raise IndexError(
                f"index {index} is out of range — buffer is empty."
            )
        if not (-n <= index < n):
            raise IndexError(
                f"index {index} is out of range — buffer has "
                f"{n} entr{'y' if n == 1 else 'ies'} "
                f"(valid range: {-n} to {n - 1})."
            )
        self._entries.pop(index)
        logger.debug(
            "Removed entry at index %d for context_id=%r",
            index,
            self.context_id,
        )

    def _drain(self) -> list["_LogEntry"]:
        """Return all buffered entries and reset the buffer.

        Called by Memory after a successful commit. Matches the
        standard checkpoint pattern: the buffer is reused across
        commits rather than discarded.
        """
        entries, self._entries = self._entries, []
        self._pending_connections = []
        return entries

    def __len__(self) -> int:
        """Return the number of pending (uncommitted) entries."""
        return len(self._entries)

    def __repr__(self) -> str:
        return (
            f"Information(context_id={self.context_id!r},"
            f" entries={len(self._entries)})"
        )


# ---------------------------------------------------------------------------
# Validation helpers — module-private
# ---------------------------------------------------------------------------


def _validate_text(text: Optional[str]) -> Optional[str]:
    if text is None:
        return None
    if not isinstance(text, str):
        raise NexusValidationError(
            f"text must be a string. Got {type(text).__name__!r}."
        )
    if not text.strip():
        raise NexusValidationError("text must not be empty.")
    return text


def _validate_image(image: Optional[Any]) -> Optional[Any]:
    if image is None:
        return None

    if isinstance(image, str):
        if image.startswith(("http://", "https://")):
            return image  # URL — reachability checked at commit time
        path = Path(image)
        if not path.is_file():
            raise NexusValidationError(
                f"Image file not found: {image}. "
                "Provide a valid file path, URL, PIL Image, "
                "numpy array, or raw bytes."
            )
        return image

    if isinstance(image, bytes):
        return image

    if isinstance(image, PILImage.Image):
        return image

    if isinstance(image, np.ndarray):
        _validate_image_ndarray(image)
        return image

    raise NexusValidationError(
        f"Unsupported image type: {type(image).__name__!r}. "
        "Provide a file path, URL, bytes, PIL Image, or numpy array."
    )


def _validate_image_ndarray(arr: np.ndarray) -> None:
    if arr.ndim not in {2, 3}:
        raise NexusValidationError(
            "Image numpy array must be 2D (H, W) or 3D (H, W, C). "
            f"Got shape {arr.shape}."
        )
    if arr.ndim == 3 and arr.shape[2] not in _IMAGE_CHANNELS:
        raise NexusValidationError(
            "Image array channel count must be 1, 3, or 4. "
            f"Got shape {arr.shape}."
        )
    if arr.dtype not in _IMAGE_DTYPES:
        raise NexusValidationError(
            f"Image array dtype must be uint8 or float32. "
            f"Got {arr.dtype}."
        )


def _validate_video(video: Optional[Any]) -> Optional[Any]:
    if video is None:
        return None

    if isinstance(video, str):
        if video.startswith(("http://", "https://")):
            return video  # URL — reachability checked at commit time
        path = Path(video)
        if not path.is_file():
            raise NexusValidationError(
                f"Video file not found: {video}. "
                "Provide a valid file path, URL, or raw bytes."
            )
        return video

    if isinstance(video, bytes):
        return video

    raise NexusValidationError(
        f"Unsupported video type: {type(video).__name__!r}. "
        "Provide a file path, URL, or bytes."
    )


def _validate_blob(
    blob: Optional[Any],
    document_type: Optional[str],
) -> tuple[Optional[Any], Optional[str]]:
    if blob is None:
        if document_type is not None:
            raise NexusValidationError(
                "document_type provided but blob is None. "
                "Provide blob=<path>, blob=<url>, or blob=<bytes> "
                "alongside document_type."
            )
        return None, None

    if isinstance(blob, str):
        if blob.startswith(("http://", "https://")):
            pass  # URL — reachability checked at commit time
        else:
            path = Path(blob)
            if not path.is_file():
                raise NexusValidationError(
                    f"Blob file not found: {blob}. "
                    "Provide a valid file path, URL, or raw bytes."
                )
    elif not isinstance(blob, bytes):
        raise NexusValidationError(
            f"blob must be a file path, URL, or bytes. "
            f"Got {type(blob).__name__!r}."
        )

    if not document_type:
        raise NexusValidationError(
            "document_type is required when blob is provided. "
            'Examples: "pdf", "mp3", "docx", "csv".'
        )

    if not isinstance(document_type, str) or not document_type.strip():
        raise NexusValidationError(
            "document_type must be a non-empty string. "
            'Examples: "pdf", "mp3", "docx".'
        )

    return blob, document_type.strip().lower()


def _validate_metadata(
    metadata: Optional[dict],
) -> Optional[dict]:
    if metadata is None:
        return None
    if not isinstance(metadata, dict):
        raise NexusValidationError(
            f"metadata must be a dict. Got {type(metadata).__name__!r}."
        )
    for key, value in metadata.items():
        if not isinstance(key, str):
            raise NexusValidationError(
                f"metadata keys must be strings. Got {type(key).__name__!r}."
            )
        if key in _RESERVED_METADATA_KEYS:
            raise NexusValidationError(
                f"metadata key {key!r} is reserved by aperture-nexus. "
                f"Use the Context fields for session/user identity."
            )
        if not isinstance(value, _METADATA_VALUE_TYPES):
            raise NexusValidationError(
                f"metadata[{key!r}] has unsupported type "
                f"{type(value).__name__!r}. "
                f"Use str, int, float, or bool."
            )
    return dict(metadata)


def _validate_embedding(
    embedding: Optional[np.ndarray],
    embedding_model: Optional[str],
) -> tuple[Optional[np.ndarray], Optional[str]]:
    if embedding is None:
        return None, None

    if not isinstance(embedding, np.ndarray):
        raise NexusValidationError(
            "embedding must be a numpy array. "
            f"Got {type(embedding).__name__!r}."
        )

    if embedding.ndim != 1:
        raise NexusValidationError(
            "embedding must be a 1D array. "
            f"Got shape {embedding.shape}."
        )

    if not np.issubdtype(embedding.dtype, np.floating):
        raise NexusValidationError(
            "embedding dtype must be a float type. "
            f"Got {embedding.dtype}."
        )

    if not embedding_model:
        raise NexusValidationError(
            "embedding_model is required when embedding is provided. "
            "Provide the name of the model that produced the embedding "
            "(e.g. 'ViT-B/16', 'text-embedding-3-small')."
        )

    if not isinstance(embedding_model, str) or not embedding_model.strip():
        raise NexusValidationError(
            "embedding_model must be a non-empty string."
        )

    if any(c in embedding_model for c in ('"', "\\")):
        raise NexusValidationError(
            f"embedding_model {embedding_model!r} contains a character that is "
            "not valid in an ApertureDB DescriptorSet name. "
            'Remove double-quotes and backslashes (e.g. use "ViT-B/16" not "ViT-B\\"16").'
        )

    if any(ord(c) < 32 for c in embedding_model):
        raise NexusValidationError(
            f"embedding_model {embedding_model!r} contains a control character. "
            "Use a plain printable string (e.g. 'ViT-B/16')."
        )

    return embedding, embedding_model.strip()
